const SPECTRAL = ['#9e0142','#d53e4f','#f46d43','#fdae61','#fee08b','#ffffbf','#e6f598','#abdda4','#66c2a5','#3288bd','#5e4fa2'];
const MOODS = [
  ['Happy','🙂','#f4cd55'],['Excited','😄','#e34f9a'],['Relaxed','😌','#2185c5'],['Tired','😴','#74a0d6'],
  ['Worried','😟','#c6dfa0'],['Sad','😢','#194f80'],['Angry','😠','#d94141'],['Stressed','😣','#3c3434'],
  ['Confused','😕','#f2dd33'],['Bored','😐','#603282'],['Playful','😜','#ee8bb2'],['Hollow','😶','#d7d7d7']
];
const todayISO = () => new Date().toISOString().slice(0,10);
const fmtDate = iso => new Date(iso+'T12:00:00').toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric'});
const clamp = (n,min,max)=>Math.min(max,Math.max(min,n));
const uid = ()=>Math.random().toString(36).slice(2,10);

const defaults = {
  habits:[
    {id:'h1',name:'Exercise',target:3,period:'week',color:SPECTRAL[8],active:true,created:todayISO()},
    {id:'h2',name:'Study',target:2,period:'day',color:SPECTRAL[10],active:true,created:todayISO()},
    {id:'h3',name:'Vitamins',target:1,period:'day',color:SPECTRAL[3],active:true,created:todayISO()},
    {id:'h4',name:'Skincare',target:1,period:'day',color:SPECTRAL[0],active:true,created:todayISO()}
  ],
  habitLogs:{}, frogs:{}, moods:{}, meals:{}, settings:{calorieGoal:1800,name:'Mild'}, version:1
};
let state = loadState();
let currentTab='today'; let habitSub='list'; let moodSub='tracker'; let progressSub='overview'; let foodDate=todayISO(); let selectedMood=null; let deferredPrompt=null;

function loadState(){try{return {...defaults,...JSON.parse(localStorage.getItem('mine-vita-state')||'{}')}}catch{return structuredClone(defaults)}}
function save(){localStorage.setItem('mine-vita-state',JSON.stringify(state));render()}
function hlog(date,id){return Number(state.habitLogs?.[date]?.[id]||0)}
function setHlog(date,id,val){state.habitLogs[date]??={}; state.habitLogs[date][id]=Math.max(0,val); save()}
function habitDoneToday(h){return hlog(todayISO(),h.id)>=h.target}
function activeHabits(){return state.habits.filter(h=>h.active!==false)}
function dayHabitPct(date){const hs=activeHabits().filter(h=>h.period==='day'); if(!hs.length)return 0;return Math.round(hs.filter(h=>hlog(date,h.id)>=h.target).length/hs.length*100)}
function getMeals(date=foodDate){return state.meals[date]||[]}
function dayNutrition(date=foodDate){return getMeals(date).reduce((a,m)=>({cal:a.cal+(+m.calories||0),protein:a.protein+(+m.protein||0),carbs:a.carbs+(+m.carbs||0),fat:a.fat+(+m.fat||0)}),{cal:0,protein:0,carbs:0,fat:0})}
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}

function render(){
  document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.tab===currentTab));
  const subtitles={today:'Your day, at a glance',habits:'Build consistency',food:'Meals & nutrition',mood:'One mood, one day',progress:'See the bigger picture'};
  document.getElementById('pageSubtitle').textContent=subtitles[currentTab];
  ({today:renderToday,habits:renderHabits,food:renderFood,mood:renderMood,progress:renderProgress}[currentTab])();
}

function renderToday(){
 const nut=dayNutrition(todayISO()); const hs=activeHabits(); const done=hs.filter(h=>habitDoneToday(h)).length; const mood=state.moods[todayISO()]; const frogs=state.frogs[todayISO()]||[];
 document.getElementById('view').innerHTML=`
  <section class="card"><div class="between row"><div><div class="muted">Good ${greeting()},</div><h2 style="margin:2px 0 0">${esc(state.settings.name||'Mild')} 🌿</h2></div><span class="pill">${fmtDate(todayISO())}</span></div>
  <div class="progress big-progress"><span style="width:${Math.min(100,nut.cal/(state.settings.calorieGoal||1800)*100)}%"></span></div><div class="between row" style="margin-top:7px"><small>${Math.round(nut.cal)} / ${state.settings.calorieGoal} kcal</small><small>${done}/${hs.length} habits</small></div></section>
  <div class="section-title">Daily summary</div><div class="grid-3">
   <div class="card metric"><small>Calories</small><strong>${Math.round(nut.cal)}</strong><small>kcal</small></div>
   <div class="card metric"><small>Habits</small><strong>${hs.length?Math.round(done/hs.length*100):0}%</strong><small>${done}/${hs.length}</small></div>
   <div class="card metric"><small>Mood</small><strong style="font-size:1rem">${mood?esc(mood.name):'—'}</strong><small>${mood?'Checked':'Not yet'}</small></div>
  </div>
  <div class="section-title between row"><span>🐸 5 Frogs Today</span><button class="link-btn" onclick="openFrogs('${todayISO()}')">Edit</button></div>
  <section class="card">${frogs.length?`<div class="frog-list">${frogs.map((f,i)=>frogRow(f,i,todayISO())).join('')}</div>`:`<div class="empty">Pick up to five things that matter today.<br><button class="secondary" onclick="openFrogs('${todayISO()}')" style="margin-top:10px">Plan today's frogs</button></div>`}</section>
  ${new Date().getDay()===0?`<div class="notice" style="margin-top:12px">🐸 Sunday planning: you can set frogs for the whole coming week now. <button class="link-btn" onclick="openWeeklyFrogs()">Plan week</button></div>`:''}
  <div class="section-title between row"><span>Today's habits</span><button class="link-btn" onclick="goTab('habits')">View all</button></div>
  <section class="card habit-list">${hs.slice(0,5).map(h=>habitMini(h)).join('')||'<div class="empty">No habits yet.</div>'}</section>
  <div class="section-title">Quick add</div><div class="grid-3"><button class="secondary" onclick="goTab('food');setTimeout(openMealModal,0)">🍎 Food</button><button class="secondary" onclick="goTab('mood')">🙂 Mood</button><button class="secondary" onclick="openHabitModal()">＋ Habit</button></div>`;
}
function greeting(){const h=new Date().getHours();return h<12?'morning':h<18?'afternoon':'evening'}
function frogRow(f,i,date){return `<label class="frog ${f.done?'done':''}"><span class="frog-num">${i+1}</span><span class="frog-text">${esc(f.text)}</span><input class="frog-check" type="checkbox" ${f.done?'checked':''} onchange="toggleFrog('${date}',${i},this.checked)"></label>`}
function toggleFrog(date,i,done){state.frogs[date][i].done=done;save()}
function habitMini(h){const n=hlog(todayISO(),h.id);return `<div class="habit" style="--habit-color:${h.color}"><div class="habit-head"><span class="habit-name"><span class="color-dot" style="background:${h.color}"></span>${esc(h.name)}</span><strong>${n}/${h.target}×</strong></div><div class="progress" style="margin-top:7px"><span style="width:${clamp(n/h.target*100,0,100)}%;background:${h.color}"></span></div></div>`}

function renderHabits(){
 const tabs=`<div class="tabs"><button class="${habitSub==='list'?'active':''}" onclick="habitSub='list';render()">Habits</button><button class="${habitSub==='calendar'?'active':''}" onclick="habitSub='calendar';render()">Calendar</button><button class="${habitSub==='report'?'active':''}" onclick="habitSub='report';render()">Reports</button></div>`;
 document.getElementById('view').innerHTML=tabs+(habitSub==='list'?habitList():habitSub==='calendar'?habitCalendar():habitReport());
}
function habitList(){return `<div class="section-title between row"><span>Active habits</span><button class="primary" onclick="openHabitModal()">＋ Add</button></div><div class="habit-list">${activeHabits().map(h=>habitCard(h)).join('')||'<div class="card empty">No active habits.</div>'}</div><div class="section-title">Paused / archived</div>${state.habits.filter(h=>h.active===false).map(h=>`<div class="card row between"><span>${esc(h.name)}</span><button class="secondary" onclick="toggleHabit('${h.id}',true)">Restore</button></div>`).join('')||'<div class="muted">Nothing here.</div>'}`}
function habitCard(h){const n=hlog(todayISO(),h.id);return `<section class="card habit" style="--habit-color:${h.color}"><div class="habit-head"><div><div class="habit-name">${esc(h.name)}</div><div class="habit-meta">${h.target} ${h.target===1?'time':'times'} per ${h.period}</div></div><strong>${n}/${h.target}×</strong></div><div class="progress" style="margin-top:10px"><span style="width:${clamp(n/h.target*100,0,100)}%;background:${h.color}"></span></div><div class="habit-actions"><button class="secondary" onclick="setHlog('${todayISO()}','${h.id}',${Math.max(0,n-1)})">−</button><button class="primary" style="background:${h.color}" onclick="setHlog('${todayISO()}','${h.id}',${n+1})">＋ Log</button><button class="secondary" onclick="openHabitModal('${h.id}')">Edit</button></div></section>`}
function toggleHabit(id,val){const h=state.habits.find(x=>x.id===id);if(h)h.active=val;save()}

function monthMatrix(ref=new Date()){const y=ref.getFullYear(),m=ref.getMonth();const first=new Date(y,m,1),days=new Date(y,m+1,0).getDate(),offset=(first.getDay()+6)%7;return {y,m,days,offset}}
let habitCalRef=new Date();
function habitCalendar(){const {y,m,days,offset}=monthMatrix(habitCalRef);const name=habitCalRef.toLocaleDateString(undefined,{month:'long',year:'numeric'});let cells='';for(let i=0;i<offset;i++)cells+='<div></div>';for(let d=1;d<=days;d++){const iso=`${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`;const pct=dayHabitPct(iso);cells+=`<button class="day ${iso===todayISO()?'today':''} ${pct===100?'complete':pct>0?'partial':''}" onclick="showHabitDay('${iso}')">${d}${pct?'<span class="dot"></span>':''}</button>`}return `<div class="section-title between row"><button class="icon-btn" onclick="habitCalRef=new Date(${y},${m-1},1);render()">‹</button><strong>${name}</strong><button class="icon-btn" onclick="habitCalRef=new Date(${y},${m+1},1);render()">›</button></div><section class="card"><div class="calendar">${['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(x=>`<div class="weekday">${x}</div>`).join('')}${cells}</div></section><section class="card" style="margin-top:12px"><div class="between row"><span>Monthly completion</span><strong>${monthlyHabitPct(y,m)}%</strong></div><div class="progress" style="margin-top:10px"><span style="width:${monthlyHabitPct(y,m)}%"></span></div></section>`}
function monthlyHabitPct(y,m){let sum=0,n=0;const days=new Date(y,m+1,0).getDate();for(let d=1;d<=days;d++){const iso=`${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`;if(iso>todayISO())continue;sum+=dayHabitPct(iso);n++}return n?Math.round(sum/n):0}
function showHabitDay(date){openModal(`<div class="modal-head"><h2>${fmtDate(date)}</h2><button class="icon-btn" onclick="closeModal()">×</button></div>${activeHabits().map(h=>`<div class="card habit" style="--habit-color:${h.color};margin:8px 0"><div class="between row"><span>${esc(h.name)}</span><strong>${hlog(date,h.id)}/${h.target}×</strong></div></div>`).join('')}`)}
function habitReport(){const days=[...Array(31)].map((_,i)=>{const d=new Date();d.setDate(d.getDate()-30+i);return d.toISOString().slice(0,10)});return `<div class="section-title">Last 31 days</div><section class="card">${activeHabits().map(h=>{const on=days.filter(d=>hlog(d,h.id)>=h.target).length;const pct=Math.round(on/days.length*100);return `<div class="report-row" style="--habit-color:${h.color}"><div class="report-title"><strong>${esc(h.name)}</strong><span>${pct}%</span></div><div class="heatmap">${days.map(d=>`<span class="heat ${hlog(d,h.id)>=h.target?'on':''}"></span>`).join('')}</div></div>`}).join('')}</section>`}

function renderFood(){const n=dayNutrition(foodDate);const meals=getMeals(foodDate);document.getElementById('view').innerHTML=`<div class="section-title between row"><button class="icon-btn" onclick="shiftFoodDate(-1)">‹</button><strong>${fmtDate(foodDate)}</strong><button class="icon-btn" onclick="shiftFoodDate(1)">›</button></div><section class="card food-summary"><div class="between row"><div class="metric"><small>Calories</small><strong>${Math.round(n.cal)}</strong><small>/ ${state.settings.calorieGoal} kcal</small></div><div class="pill">${Math.max(0,state.settings.calorieGoal-Math.round(n.cal))} remaining</div></div><div class="progress big-progress"><span style="width:${clamp(n.cal/state.settings.calorieGoal*100,0,100)}%;background:var(--orange)"></span></div><div class="grid-3" style="margin-top:12px"><div class="macro"><strong>${Math.round(n.protein)}g</strong><small>Protein</small></div><div class="macro"><strong>${Math.round(n.carbs)}g</strong><small>Carbs</small></div><div class="macro"><strong>${Math.round(n.fat)}g</strong><small>Fat</small></div></div></section><div class="section-title between row"><span>Meals</span><button class="primary" onclick="openMealModal()">＋ Add food</button></div><div class="meal-list">${meals.length?meals.map(m=>mealCard(m)).join(''):'<div class="card empty">No food logged yet.</div>'}</div><div class="notice" style="margin-top:12px">📷 AI photo recognition is scaffolded as the next build step. For now, photo upload + manual nutrition logging works.</div>`}
function shiftFoodDate(delta){const d=new Date(foodDate+'T12:00:00');d.setDate(d.getDate()+delta);foodDate=d.toISOString().slice(0,10);render()}
function mealCard(m){return `<section class="card meal">${m.photo?`<img class="meal-photo" src="${m.photo}" alt="Meal photo">`:`<div class="meal-photo">🍽️</div>`}<div class="meal-info"><strong>${esc(m.name)}</strong><small>${m.calories} kcal · P ${m.protein||0}g · C ${m.carbs||0}g · F ${m.fat||0}g</small>${m.note?`<small style="display:block;margin-top:4px">${esc(m.note)}</small>`:''}</div><button class="icon-btn" onclick="deleteMeal('${foodDate}','${m.id}')">×</button></section>`}
function deleteMeal(date,id){state.meals[date]=(state.meals[date]||[]).filter(m=>m.id!==id);save()}

function renderMood(){const tabs=`<div class="tabs"><button class="${moodSub==='tracker'?'active':''}" onclick="moodSub='tracker';render()">Today</button><button class="${moodSub==='history'?'active':''}" onclick="moodSub='history';render()">History</button><button class="${moodSub==='calendar'?'active':''}" onclick="moodSub='calendar';render()">Calendar</button><button class="${moodSub==='insights'?'active':''}" onclick="moodSub='insights';render()">Insights</button></div>`;document.getElementById('view').innerHTML=tabs+(moodSub==='tracker'?moodTracker():moodSub==='history'?moodHistory():moodSub==='calendar'?moodCalendar():moodInsights())}
function moodTracker(){const existing=state.moods[todayISO()];selectedMood=selectedMood||existing?.name||null;return `<div class="section-title">How are you feeling today?</div><div class="mood-grid">${MOODS.map(([name,face,color])=>`<button class="mood-choice ${selectedMood===name?'selected':''}" style="background:${color}28" onclick="selectedMood='${name}';render()"><span class="face">${face}</span><small>${name}</small></button>`).join('')}</div><section class="card" style="margin-top:14px"><div class="field"><label>Note (optional)</label><textarea id="moodNote" placeholder="What's on your mind?">${esc(existing?.note||'')}</textarea></div><button class="primary wide" onclick="saveMood()">${existing?'Update':'Save'} mood</button></section>${existing?`<div class="section-title">Today's mood</div>${moodEntryCard(todayISO(),existing)}`:''}`}
function saveMood(){if(!selectedMood)return alert('Choose a mood first.');const info=MOODS.find(m=>m[0]===selectedMood);state.moods[todayISO()]={name:info[0],face:info[1],color:info[2],note:document.getElementById('moodNote').value.trim(),time:new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})};save()}
function moodEntryCard(date,m){return `<section class="card note-card" style="--mood-color:${m.color};margin:9px 0"><div class="between row"><strong>${m.face} ${esc(m.name)}</strong><small class="muted">${fmtDate(date)}</small></div>${m.note?`<p style="margin-bottom:0">${esc(m.note)}</p>`:'<p class="muted" style="margin-bottom:0">No note</p>'}</section>`}
function moodHistory(){const entries=Object.entries(state.moods).sort((a,b)=>b[0].localeCompare(a[0]));return `<div class="section-title">Mood history</div>${entries.length?entries.map(([d,m])=>`<div onclick="openMoodEntry('${d}')" style="cursor:pointer">${moodEntryCard(d,m)}</div>`).join(''):'<div class="card empty">No mood entries yet.</div>'}`}
function openMoodEntry(date){const m=state.moods[date];openModal(`<div class="modal-head"><h2>${m.face} ${esc(m.name)}</h2><button class="icon-btn" onclick="closeModal()">×</button></div><p class="muted">${fmtDate(date)} · ${esc(m.time||'')}</p><p>${esc(m.note||'No note')}</p><button class="secondary wide" onclick="deleteMood('${date}')">Delete entry</button>`)}
function deleteMood(date){delete state.moods[date];selectedMood=null;closeModal();save()}
let moodCalRef=new Date();
function moodCalendar(){const {y,m,days,offset}=monthMatrix(moodCalRef);let cells='';for(let i=0;i<offset;i++)cells+='<div></div>';for(let d=1;d<=days;d++){const iso=`${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`;const md=state.moods[iso];cells+=`<button class="day ${iso===todayISO()?'today':''}" style="${md?`background:${md.color}40`:''}" onclick="${md?`openMoodEntry('${iso}')`:`void 0`}">${d}${md?`<span class="dot" style="background:${md.color}"></span>`:''}</button>`}return `<div class="section-title between row"><button class="icon-btn" onclick="moodCalRef=new Date(${y},${m-1},1);render()">‹</button><strong>${moodCalRef.toLocaleDateString(undefined,{month:'long',year:'numeric'})}</strong><button class="icon-btn" onclick="moodCalRef=new Date(${y},${m+1},1);render()">›</button></div><section class="card"><div class="calendar">${['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(x=>`<div class="weekday">${x}</div>`).join('')}${cells}</div></section>`}
function moodInsights(){const now=new Date();const prefix=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}`;const vals=Object.entries(state.moods).filter(([d])=>d.startsWith(prefix)).map(([,m])=>m);const counts={};vals.forEach(m=>counts[m.name]=(counts[m.name]||0)+1);const sorted=Object.entries(counts).sort((a,b)=>b[1]-a[1]);let cumulative=0;const gradients=sorted.map(([name,n])=>{const mood=MOODS.find(m=>m[0]===name);const start=cumulative; cumulative+=n/Math.max(vals.length,1)*100;return `${mood?.[2]||'#ccc'} ${start}% ${cumulative}%`});return `<div class="section-title">${now.toLocaleDateString(undefined,{month:'long',year:'numeric'})}</div><section class="card">${vals.length?`<div class="donut" style="background:conic-gradient(${gradients.join(',')})"><div class="donut-center">${vals.length}<br><small>entries</small></div></div><div class="legend">${sorted.map(([name,n])=>{const mood=MOODS.find(m=>m[0]===name);return `<button class="legend-row" style="border:0;background:none;cursor:pointer" onclick="showMoodType('${name}')"><span><span class="color-dot" style="background:${mood[2]}"></span>${name}</span><strong>${Math.round(n/vals.length*100)}%</strong></button>`}).join('')}</div>`:'<div class="empty">Log moods this month to see your breakdown.</div>'}</section>`}
function showMoodType(name){const entries=Object.entries(state.moods).filter(([,m])=>m.name===name).sort((a,b)=>b[0].localeCompare(a[0]));openModal(`<div class="modal-head"><h2>${name} notes</h2><button class="icon-btn" onclick="closeModal()">×</button></div>${entries.map(([d,m])=>moodEntryCard(d,m)).join('')||'<div class="empty">No entries.</div>'}`)}

function renderProgress(){const tabs=`<div class="tabs"><button class="${progressSub==='overview'?'active':''}" onclick="progressSub='overview';render()">Overview</button><button class="${progressSub==='habits'?'active':''}" onclick="progressSub='habits';render()">Habits</button><button class="${progressSub==='nutrition'?'active':''}" onclick="progressSub='nutrition';render()">Nutrition</button><button class="${progressSub==='mood'?'active':''}" onclick="progressSub='mood';render()">Mood</button></div>`;document.getElementById('view').innerHTML=tabs+(progressSub==='overview'?progressOverview():progressSub==='habits'?habitReport():progressSub==='nutrition'?nutritionProgress():moodInsights())}
function last7(){return [...Array(7)].map((_,i)=>{const d=new Date();d.setDate(d.getDate()-6+i);return d.toISOString().slice(0,10)})}
function progressOverview(){const days=last7();const hp=Math.round(days.reduce((s,d)=>s+dayHabitPct(d),0)/7);const avg=Math.round(days.reduce((s,d)=>s+dayNutrition(d).cal,0)/7);const moodCounts={};days.forEach(d=>{const m=state.moods[d];if(m)moodCounts[m.name]=(moodCounts[m.name]||0)+1});const common=Object.entries(moodCounts).sort((a,b)=>b[1]-a[1])[0]?.[0]||'—';return `<div class="section-title">This week</div><div class="grid-2"><div class="card metric"><small>Habit completion</small><strong>${hp}%</strong></div><div class="card metric"><small>Average calories</small><strong>${avg}</strong><small>kcal/day</small></div><div class="card metric"><small>Most common mood</small><strong style="font-size:1.1rem">${common}</strong></div><div class="card metric"><small>Meals logged</small><strong>${days.reduce((s,d)=>s+getMeals(d).length,0)}</strong></div></div><div class="section-title">Habit completion</div><section class="card">${barChart(days.map(d=>dayHabitPct(d)),days.map(d=>new Date(d+'T12:00').toLocaleDateString(undefined,{weekday:'short'})))}</section>`}
function barChart(vals,labels){const max=Math.max(...vals,100);return `<div class="chart-bars">${vals.map((v,i)=>`<div class="bar-wrap"><div class="bar" style="height:${Math.max(5,v/max*120)}px"></div><div>${labels[i]}</div><strong>${Math.round(v)}%</strong></div>`).join('')}</div>`}
function nutritionProgress(){const days=last7();const vals=days.map(d=>dayNutrition(d).cal);const max=Math.max(...vals,state.settings.calorieGoal,1);return `<div class="section-title">Calories · last 7 days</div><section class="card"><div class="chart-bars">${vals.map((v,i)=>`<div class="bar-wrap"><div class="bar" style="height:${Math.max(5,v/max*120)}px;background:var(--orange)"></div><div>${new Date(days[i]+'T12:00').toLocaleDateString(undefined,{weekday:'short'})}</div><strong>${Math.round(v)}</strong></div>`).join('')}</div></section>`}

function openHabitModal(id){const h=id?state.habits.find(x=>x.id===id):null;const selected=h?.color||SPECTRAL[8];openModal(`<div class="modal-head"><h2>${h?'Edit':'Add'} habit</h2><button class="icon-btn" onclick="closeModal()">×</button></div><div class="field"><label>Habit name</label><input id="habitName" value="${esc(h?.name||'')}" placeholder="e.g. Exercise"></div><div class="field"><label>Target (times)</label><input id="habitTarget" type="number" min="1" max="50" value="${h?.target||1}"></div><div class="field"><label>Period</label><select id="habitPeriod"><option value="day" ${h?.period==='day'?'selected':''}>Day</option><option value="week" ${h?.period==='week'?'selected':''}>Week</option><option value="month" ${h?.period==='month'?'selected':''}>Month</option></select></div><div class="field"><label>Colour · Spectral palette</label><div class="palette" id="palette">${SPECTRAL.map(c=>`<button class="swatch ${c===selected?'selected':''}" data-color="${c}" style="background:${c}" onclick="document.querySelectorAll('.swatch').forEach(x=>x.classList.remove('selected'));this.classList.add('selected')"></button>`).join('')}</div></div><button class="primary wide" onclick="saveHabit('${id||''}')">Save habit</button>${h?`<button class="secondary wide" style="margin-top:8px" onclick="toggleHabit('${h.id}',false);closeModal()">Pause / archive</button>`:''}`)}
function saveHabit(id){const name=document.getElementById('habitName').value.trim(),target=+document.getElementById('habitTarget').value,period=document.getElementById('habitPeriod').value,color=document.querySelector('.swatch.selected')?.dataset.color||SPECTRAL[8];if(!name||target<1)return alert('Add a habit name and target.');if(id){Object.assign(state.habits.find(h=>h.id===id),{name,target,period,color})}else state.habits.push({id:uid(),name,target,period,color,active:true,created:todayISO()});closeModal();save()}
function openFrogs(date){const list=state.frogs[date]||[];openModal(`<div class="modal-head"><h2>🐸 Frogs · ${fmtDate(date)}</h2><button class="icon-btn" onclick="closeModal()">×</button></div><p class="muted">Up to 5 priorities. You can plan future days too.</p>${[0,1,2,3,4].map(i=>`<div class="field"><label>Frog ${i+1}</label><input class="frog-input" value="${esc(list[i]?.text||'')}" placeholder="Priority ${i+1}"></div>`).join('')}<button class="primary wide" onclick="saveFrogs('${date}')">Save frogs</button><div class="field"><label>Plan another date</label><input type="date" id="frogDate" min="${todayISO()}" value="${date}" onchange="openFrogs(this.value)"></div>`)}
function saveFrogs(date){const old=state.frogs[date]||[];state.frogs[date]=[...document.querySelectorAll('.frog-input')].map((x,i)=>({text:x.value.trim(),done:old[i]?.text===x.value.trim()?!!old[i].done:false})).filter(x=>x.text);closeModal();save()}
function openWeeklyFrogs(){const start=new Date();const monday=new Date(start);monday.setDate(start.getDate()+((8-start.getDay())%7));openModal(`<div class="modal-head"><h2>🐸 Plan next week</h2><button class="icon-btn" onclick="closeModal()">×</button></div><p class="muted">Choose a day to add its five frogs.</p>${[0,1,2,3,4,5,6].map(i=>{const d=new Date(monday);d.setDate(monday.getDate()+i);const iso=d.toISOString().slice(0,10);return `<button class="secondary wide" style="margin:5px 0" onclick="openFrogs('${iso}')">${fmtDate(iso)}</button>`}).join('')}`)}
function openMealModal(){openModal(`<div class="modal-head"><h2>Add food</h2><button class="icon-btn" onclick="closeModal()">×</button></div><div class="field"><label>Meal / food name</label><input id="mealName" placeholder="e.g. Chicken rice bowl"></div><div class="field"><label>Photo (optional)</label><input id="mealPhoto" type="file" accept="image/*" capture="environment" onchange="previewMealPhoto(this)"><img id="mealPreview" class="photo-preview hidden" alt="Preview"></div><div class="grid-2"><div class="field"><label>Calories</label><input id="mealCal" type="number" min="0" value="0"></div><div class="field"><label>Protein (g)</label><input id="mealProtein" type="number" min="0" value="0"></div><div class="field"><label>Carbs (g)</label><input id="mealCarbs" type="number" min="0" value="0"></div><div class="field"><label>Fat (g)</label><input id="mealFat" type="number" min="0" value="0"></div></div><div class="field"><label>Note (optional)</label><textarea id="mealNote"></textarea></div><button class="primary wide" onclick="saveMeal()">Save meal</button><div class="notice" style="margin-top:10px">AI food identification + nutrition database matching comes in the next build phase.</div>`)}
let pendingMealPhoto='';function previewMealPhoto(input){const f=input.files?.[0];if(!f)return;const r=new FileReader();r.onload=e=>{pendingMealPhoto=e.target.result;const img=document.getElementById('mealPreview');img.src=pendingMealPhoto;img.classList.remove('hidden')};r.readAsDataURL(f)}
function saveMeal(){const name=document.getElementById('mealName').value.trim();if(!name)return alert('Add a food or meal name.');state.meals[foodDate]??=[];state.meals[foodDate].push({id:uid(),name,calories:+document.getElementById('mealCal').value||0,protein:+document.getElementById('mealProtein').value||0,carbs:+document.getElementById('mealCarbs').value||0,fat:+document.getElementById('mealFat').value||0,note:document.getElementById('mealNote').value.trim(),photo:pendingMealPhoto});pendingMealPhoto='';closeModal();save()}

function openModal(html){const dlg=document.getElementById('modal');document.getElementById('modalContent').innerHTML=html;if(dlg.open)dlg.close();dlg.showModal()}
function closeModal(){document.getElementById('modal').close()}
function goTab(tab){currentTab=tab;render()}
window.goTab=goTab;

document.querySelectorAll('.nav-item').forEach(b=>b.addEventListener('click',()=>{currentTab=b.dataset.tab;render()}));
document.getElementById('modal').addEventListener('click',e=>{if(e.target.id==='modal')closeModal()});
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;document.getElementById('installBtn').classList.remove('hidden')});
document.getElementById('installBtn').addEventListener('click',async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;document.getElementById('installBtn').classList.add('hidden')}});
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));
render();
